# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from movement/accgyro.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import std_msgs.msg

class accgyro(genpy.Message):
  _md5sum = "38ea6143b493167fb723479a442558f8"
  _type = "movement/accgyro"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """std_msgs/Float32 accx
std_msgs/Float32 accy
std_msgs/Float32 accz
std_msgs/Float32 gyrox
std_msgs/Float32 gyroy
std_msgs/Float32 gyroz

================================================================================
MSG: std_msgs/Float32
float32 data"""
  __slots__ = ['accx','accy','accz','gyrox','gyroy','gyroz']
  _slot_types = ['std_msgs/Float32','std_msgs/Float32','std_msgs/Float32','std_msgs/Float32','std_msgs/Float32','std_msgs/Float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       accx,accy,accz,gyrox,gyroy,gyroz

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(accgyro, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.accx is None:
        self.accx = std_msgs.msg.Float32()
      if self.accy is None:
        self.accy = std_msgs.msg.Float32()
      if self.accz is None:
        self.accz = std_msgs.msg.Float32()
      if self.gyrox is None:
        self.gyrox = std_msgs.msg.Float32()
      if self.gyroy is None:
        self.gyroy = std_msgs.msg.Float32()
      if self.gyroz is None:
        self.gyroz = std_msgs.msg.Float32()
    else:
      self.accx = std_msgs.msg.Float32()
      self.accy = std_msgs.msg.Float32()
      self.accz = std_msgs.msg.Float32()
      self.gyrox = std_msgs.msg.Float32()
      self.gyroy = std_msgs.msg.Float32()
      self.gyroz = std_msgs.msg.Float32()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.accx.data, _x.accy.data, _x.accz.data, _x.gyrox.data, _x.gyroy.data, _x.gyroz.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.accx is None:
        self.accx = std_msgs.msg.Float32()
      if self.accy is None:
        self.accy = std_msgs.msg.Float32()
      if self.accz is None:
        self.accz = std_msgs.msg.Float32()
      if self.gyrox is None:
        self.gyrox = std_msgs.msg.Float32()
      if self.gyroy is None:
        self.gyroy = std_msgs.msg.Float32()
      if self.gyroz is None:
        self.gyroz = std_msgs.msg.Float32()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.accx.data, _x.accy.data, _x.accz.data, _x.gyrox.data, _x.gyroy.data, _x.gyroz.data,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6f().pack(_x.accx.data, _x.accy.data, _x.accz.data, _x.gyrox.data, _x.gyroy.data, _x.gyroz.data))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.accx is None:
        self.accx = std_msgs.msg.Float32()
      if self.accy is None:
        self.accy = std_msgs.msg.Float32()
      if self.accz is None:
        self.accz = std_msgs.msg.Float32()
      if self.gyrox is None:
        self.gyrox = std_msgs.msg.Float32()
      if self.gyroy is None:
        self.gyroy = std_msgs.msg.Float32()
      if self.gyroz is None:
        self.gyroz = std_msgs.msg.Float32()
      end = 0
      _x = self
      start = end
      end += 24
      (_x.accx.data, _x.accy.data, _x.accz.data, _x.gyrox.data, _x.gyroy.data, _x.gyroz.data,) = _get_struct_6f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6f = None
def _get_struct_6f():
    global _struct_6f
    if _struct_6f is None:
        _struct_6f = struct.Struct("<6f")
    return _struct_6f
